POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "id": 0,
  "image": "",
  "login": "aaa",
  "password": "0000"
}

###
GET http://localhost:8080/question/info/1

###
POST http://localhost:8080/answer/setBest/1

###
POST http://localhost:8080/user/update
Content-Type: application/json

{
  "id": 1,
  "image": "https://modamix.net/wp-content/uploads/2020/04/EMCwMwpWoAAa4Yz.jpg",
  "login": "aaa",
  "password": "0000"
}


###
POST http://localhost:8080/question/update
Content-Type: application/json

{
  "id": 1,
  "subcategoryId": 1,
  "userId": 1,
  "title": "uio",
  "description": "123"
}

###
POST http://localhost:8080/question/createScore
Content-Type: application/json

{
  "id": 0,
  "questionId": 1,
  "userId": 1,
  "score": "123"
}

###
POST http://localhost:8080/question/forUser/1
Content-Type: application/json

{
  "sorting": "ALPHABET",
  "dateFrom": "2020-05-17"
}